name: CI

permissions:
  issues: write      # comment/update issue comments
  contents: read     # read the repo

on:
  pull_request:                           # for building & training
    types: [opened, synchronize, reopened]
  pull_request_target:                    # for posting comments
    types: [opened, synchronize, reopened]

jobs:
  build-and-train:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.12.10' }
      - run: |
          pip install --upgrade pip
          pip install torch torchvision
      - run: python train.py --epochs 3 --batch-size 32
      - run: |
          echo "..." > metrics.json

  comment:
    if: github.event_name == 'pull_request_target'
    needs: build-and-train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4             # checks out the base for safety
      - name: Post metrics as PR comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Training Report
            - **Accuracy:** $(jq .accuracy metrics.json)
            - **Loss:** $(jq .loss metrics.json)
