name: CI

permissions:
  contents: read     # you only need read if you’re not writing code back
  issues: write      # required so create-or-update-comment can post

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4.2.2
        with:
          # by default pull_request_target checks out the base; this forces HEAD
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref:        ${{ github.event.pull_request.head.ref }}
          token:      ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.12.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision

      - name: Run quick training
        run: |
          python train.py --epochs 1 --batch-size 32
      
      - name: Validate metrics file
        run: |
          if [ ! -f metrics.json ]; then
            echo "metrics.json file is missing!"
            exit 1
          fi
          jq .accuracy metrics.json >/dev/null || (echo "Malformed metrics.json file" && exit 1)
      
      - name: Install jq
        run: sudo apt-get install -y jq
      
      - name: Generate metrics comment
        id: generate_comment
        run: |
          ACCURACY=$(jq .accuracy metrics.json)
          LOSS=$(jq .loss metrics.json)
          echo "COMMENT=### Training Report\n- **Accuracy:** $ACCURACY\n- **Loss:** $LOSS" >> $GITHUB_ENV
      
      - name: Post metrics as PR comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ env.COMMENT }}
