# This is a basic workflow to help you get started with Actions

name: CI

permissions:
  issues: write
  
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision   # plus any others

      - name: Run quick training
        run: |
          python train.py --epochs 3 --batch-size 32

      - name: Post metrics as PR comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number || github.run_id }}
          body: |
            ### Training Report
            - **Accuracy:** $(jq .accuracy metrics.json)
            - **Loss:** $(jq .loss metrics.json)
